#!/bin/sh

if [ -f [[deploy.home]]/[[artifactId]].jar ] ; then
    rm [[deploy.home]]/[[artifactId]].jar
  fi

ln -sf [[deploy.home]]/[[deploy.final-name]]-shade.jar [[deploy.home]]/[[artifactId]].jar

chown [[deploy.user]]:[[deploy.group]] [[deploy.home]]/[[artifactId]].jar

if grep -q -l `printf '\r\n'` /etc/init/[[deploy.service-name]].conf ; then
  echo "Upstart conf file in Windows format converting"
  sed -i 's/\r//g' /etc/init/[[deploy.service-name]].conf
fi

stop [[deploy.service-name]]
start [[deploy.service-name]]

exit 0
