# **Note** that config order in this file is important since what comes afterwards takes precedence
version = "3.8.6"
runner.dialect = scala213source3
project.git = true
align.preset = true
align.arrowEnumeratorGenerator = true
align.tokens = [
  {code = "=>", owner = "Case"},
  {code = "<-", owner = "for"},
  "%",
  "%%"]
align.openParenDefnSite = false #Scalafmt default
align.openParenCallSite = false
binPack.parentConstructors = false #Scalafmt default
indent.callSite = 2 #Scalafmt default
indent.defnSite = 2
danglingParentheses {
  callSite = true
  ctrlSite = true
  defnSite = true
}
docstrings.style = Asterisk
includeCurlyBraceInSelectChains = true #Scalafmt default
maxColumn = 160
newlines.penalizeSingleSelectMultiArgList = false #Scalafmt default
rewrite {
  rules = [
    RedundantParens,
    SortImports,
    RedundantBraces,
    PreferCurlyFors
  ]
  redundantBraces {
    maxLines = 3
    stringInterpolation = true
  }
  tokens = {
    "⇒": "=>"
    "→": "->"
    "←": "<-"
  }
}
fileOverride {
  "glob:**/mauth-signer-http4s-022/**" {
    runner.dialect = scala213
  }
  "glob:**/mauth-signer-akka-http/**" {
    runner.dialect = scala213
  }
  "glob:**/mauth-sender-sttp-akka-http/**" {
    runner.dialect = scala213
  }
  "glob:**/mauth-authenticator-akka-http/**" {
    runner.dialect = scala213
  }
}
onTestFailure = "To fix this, run 'sbt scalafmtAll scalafmtSbt' from the project root directory"
