= Contributing

. Clone this repo by executing in your workspace. Checkout `develop` branch
[source,bash]
----
$ git clone git@github.com:mdsol/mauth-jvm-clients.git
$ cd mauth-jvm-clients
$ git checkout develop
----

This repo contains the submodule `mauth-protocol-test-suite` so requires a flag when initially cloning in order to clone and init submodules.
----
$ git clone --recurse-submodules git@github.com:mdsol/mauth-jvm-clients.git
----

If you have already cloned before the submodule was introduced, then run:
----
$ cd mauth-protocol-test-suite
$ git submodule update --init
----

== Git Hooks
Install desired hook(s)

[source,bash]
----
dev-config/hooks/pre-commit-hook-install.sh # Run scalafmt for file on the commit
----

== Continuous Integration Server (Travis)

Travis server is configured via .travis.yml file. To get environment variable in to the build container
`SONATYPE_USER` and `SONATYPE_TOKEN` should be defined on travis settings.

== Deploying artifacts

Travis CI is setup to deploy artifacts, built jar and sources jar to maven repo after each successful build.

Make sure that the version number has `-SNAPSHOT` in all branches but master as maven repo will only allow one artifact without SNAPSHOT

== Releasing

To release

. Checkout `master`
. Merge `develop` to `master`
. Change version number to match release without `-SNAPSHOT`. e.g. `2016.1.1`
. Push
. Go to https://github.com/mdsol/mauth-jvm-clients/releases[Releases] tab on github and tag with the version number
