= Contributing

. Clone this repo by executing in your workspace. Checkout `develop` branch
[source,bash]
----
$ git clone git@github.com:mdsol/mauth-jvm-clients.git
$ cd mauth-jvm-clients
$ git checkout develop
----

== Git Hooks
Install desired hook(s)

[source,bash]
----
dev-config/hooks/pre-commit-hook-install.sh # Run scalafmt for file on the commit
----

== Continuous Integration Server (Travis)

Travis server is configured via .travis.yml file. To get environment variable in to the build container
`SONATYPE_USER` and `SONATYPE_TOKEN` should be defined on travis settings.

== Deploying artifacts

Travis CI is setup to deploy artifacts, built jar and sources jar to maven repo after each successful build.

Make sure that the version number has `-SNAPSHOT` in all branches but master as maven repo will only allow one artifact without SNAPSHOT

== Releasing

To release

. Checkout `master`
. Merge `develop` to `master`
. Change version number to match release without `-SNAPSHOT`. e.g. `2016.1.1`
. Push
. Go to https://github.com/mdsol/mauth-jvm-clients/releases[Releases] tab on github and tag with the version number


== Running mauth-protocol-test-suite

To run the mauth-protocol-test-suite clone the latest test suite onto your machine and place it in the same parent directory as this repo (or supply the ENV var `TEST_SUITE_RELATIVE_PATH` with the path to the test suite relative to this repo). Then run:

----
sbt "test:testOnly *ProtocolSuiteSpec"
----