= MAuth Signer Using Apache HttpClient

This is an implementation of Medidata Authentication Client Signer to sign the Http requests

== Usage
. Configuration
* MAuth uses https://github.com/typesafehub/config[Typesafe Config].
 Create `application.conf` on your classpath with the following content. The mauth_sign_requests option can be set to sign outgoing requests with Comma-separated protocol versions to sign requests. the default is v2. If the both v1 and v2 specified, the client sign requests with both x-mws-xxxxx and mcc-xxxxx headers

----
app {
   uuid: "aaaa-bbbbb-ccccc-ddddd-eeeee"
   private_key: "avasdfasdfadf"
}
----

. Signing Requests
* To sign requests using Apache HttpClient interceptors, please see link:src/example/java/com/mdsol/mauth/MauthRequestInterceptorSignerExample.java[com.mdsol.mauth.MauthRequestInterceptorSignerExample]
* To sign requests manually, please see link:src/example/java/com/mdsol/mauth/ManualSignerExample.java[com.mdsol.mauth.ManualSignerExample]
