name: Continuous Integration
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
permissions:
  contents: write

env:
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  test_and_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:11
      - name: Lint
        run: sbt "scalafmtSbtCheck;scalafmtCheckAll"
      - name: Test
        run: sbt "+test"
        env:
          APP_MAUTH_UUID: 398ea708-50eb-499f-98d3-14cc7692668c
          APP_MAUTH_PRIVATE_KEY: ${{ secrets.FAKE_PRIVATE_KEY }}
      - name: Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}