name: Continuous Integration
on:
  push:
    branches:
      - "**"
    tags:
      - "v*"
permissions:
  contents: write

env:
  ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_USERNAME }}
  ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}

jobs:
  test_and_release:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4
        with:
          submodules: recursive
      - uses: coursier/cache-action@142d2738bd29f0eb9d44610828acb3a19809feab # ratchet:coursier/cache-action@v6
      - name: Set up JDK 21
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # ratchet:actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'sbt'
      - uses: sbt/setup-sbt@26ab4b0fa1c47fa62fc1f6e51823a658fb6c760c # ratchet:sbt/setup-sbt@v1
      - name: Lint
        run: sbt "scalafmtSbtCheck;scalafmtCheckAll"
      - name: Test
        run: sbt "+test"
        env:
          APP_MAUTH_UUID: 398ea708-50eb-499f-98d3-14cc7692668c
          APP_MAUTH_PRIVATE_KEY: ${{ secrets.FAKE_PRIVATE_KEY }}
      - name: Release
        if: ${{ startsWith(github.ref, 'refs/tags/v') }}
        run: sbt ci-release
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
